//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PurchaseOrders.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseOrderDetails
    {
        public int IdOrderDetail { get; set; }
        public int IdOrder { get; set; }
        public int IdProduct { get; set; }
        public int Sequence { get; set; }
        public decimal Amount { get; set; }
        public decimal Total { get; set; }
        public string Comments { get; set; }
    
        public virtual Products Products { get; set; }
        public virtual PurchaseOrders PurchaseOrders { get; set; }
    }
}
